name: Backdrop Handbook
permalink: /:categories/:title/

# BASE_PATH is set to "/" in includes/setup.html if site.safe is FALSE.
base_path: /handbook/

include: ['_pages']
relative_permalinks: false

markdown: redcarpet
pygments: true

redcarpet:
  extensions: [
    "hard_wrap",
    "no_intra_emphasis",
    "fenced_code_blocks",
    "autolink",
    "tables",
    "with_toc_data",
    "strikethrough",
    "superscript",
    "no_intra_emphasis"
  ]
