name: Backdrop Handbook
permalink: /:categories/:title/
BASE_PATH: /handbook

include: ['_pages']
relative_permalinks: false

# maruku is used on Github pages itself. You may need to "gem install maruku" to
# render pages correctly. We use maruku-specific syntax for generating table of
# contents in pages. See http://maruku.rubyforge.org/maruku.html
markdown: redcarpet
pygments: true

redcarpet:
  extensions: [
    "hard_wrap",
    "no_intra_emphasis",
    "fenced_code_blocks",
    "autolink",
    "tables",
    "with_toc_data",
    "strikethrough",
    "superscript",
    "no_intra_emphasis"
  ]
